# Generated by Django 3.2.8 on 2022-09-30 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_auto_20220930_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=100)),
                ('ctc', models.CharField(max_length=100)),
                ('breakdown', models.TextField(max_length=500)),
                ('job_desc', models.TextField(max_length=2000)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.year')),
            ],
        ),
        migrations.CreateModel(
            name='AllowedBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.branch')),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.drive')),
            ],
        ),
    ]
