# Generated by Django 4.1.2 on 2022-11-25 17:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='breakdown',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='drive',
            name='job_desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
