# Generated by Django 4.1.2 on 2022-11-22 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctc', models.FloatField(default=0)),
                ('base', models.FloatField(default=0)),
                ('cgpa', models.FloatField(default=0)),
                ('total_offers', models.IntegerField(default=0)),
                ('year', models.FloatField(default=2022)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
