# Generated by Django 4.1.2 on 2022-12-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentYear',
            fields=[
                ('year', models.IntegerField(default='22', primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='companydatabase',
            old_name='company_id',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='companydatabase',
            name='base',
        ),
        migrations.RemoveField(
            model_name='companydatabase',
            name='cgpa',
        ),
        migrations.AddField(
            model_name='companydatabase',
            name='Btech',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companydatabase',
            name='Dtech',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companydatabase',
            name='MBA',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companydatabase',
            name='MSC',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companydatabase',
            name='Mtech',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companydatabase',
            name='total_offers',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companydatabase',
            name='year',
            field=models.BigIntegerField(default=2022),
        ),
    ]
