# Generated by Django 4.1.2 on 2022-12-06 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_presentyear_rename_company_id_companydatabase_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='type',
        ),
    ]
