# Generated by Django 4.1.2 on 2022-12-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_linkd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='linkd',
            field=models.CharField(default='', max_length=500),
        ),
    ]
